### ISSUE TITLE
how to use this bot

### ISSUE THREAD

**Issue by ItzKazuki** [Douile/discord-gamestatus#25]
Hi I have followed the instructions but still showing error :) pls help
`/root/discord-gamestatus/src/limits.js:19
  onError ||= debugLog;
          ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/discord-gamestatus/src/structs/UpdateCache.js:26:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)`

**Comment by Douile** [comment]
Make sure you are using node version 16 or greater
